<a href="https://colab.research.google.com/github/netfron/auto-ml-test/blob/master/autokeras_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install autokeras

import numpy as np
import tensorflow as tf
from keras.datasets import mnist

import autokeras as ak

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train[:100]
y_train = y_train[:100]
x_test = x_test[:100]
y_test = y_test[:100]
print(x_train.shape)  # (60000, 28, 28)
print(y_train.shape)  # (60000,)
print(y_train[:3])  # array([7, 2, 1], dtype=uint8)

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
(100, 28, 28)
(100,)
[5 0 4]


In [2]:
# Initialize the image classifier.
clf = ak.ImageClassifier(overwrite=True, max_trials=1)
# Feed the image classifier with training data.
clf.fit(x_train, y_train, epochs=1)


# Predict with the best model.
predicted_y = clf.predict(x_test)
print(predicted_y)


# Evaluate the best model with testing data.
print(clf.evaluate(x_test, y_test))

Trial 1 Complete [00h 00m 04s]
val_loss: 2.1313207149505615

Best val_loss So Far: 2.1313207149505615
Total elapsed time: 00h 00m 04s
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 54ms/step - accuracy: 0.1633 - loss: 2.3027
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step

/usr/local/lib/python3.10/dist-packages/keras/src/saving/saving_lib.py:418: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 14 variables. 
  trackable.load_own_variables(weights_store.get(inner_path))


4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
[['9']
 ['1']
 ['1']
 ['0']
 ['4']
 ['1']
 ['4']
 ['1']
 ['4']
 ['9']
 ['0']
 ['0']
 ['9']
 ['0']
 ['1']
 ['0']
 ['4']
 ['3']
 ['3']
 ['4']
 ['9']
 ['6']
 ['0']
 ['3']
 ['4']
 ['0']
 ['4']
 ['4']
 ['0']
 ['1']
 ['3']
 ['1']
 ['3']
 ['0']
 ['9']
 ['3']
 ['4']
 ['1']
 ['1']
 ['1']
 ['1']
 ['9']
 ['4']
 ['1']
 ['1']
 ['3']
 ['1']
 ['4']
 ['4']
 ['4']
 ['1']
 ['3']
 ['0']
 ['3']
 ['4']
 ['0']
 ['4']
 ['1']
 ['4']
 ['9']
 ['4']
 ['0']
 ['1']
 ['9']
 ['4']
 ['1']
 ['0']
 ['4']
 ['3']
 ['0']
 ['3']
 ['0']
 ['3']
 ['9']
 ['1']
 ['1']
 ['3']
 ['4']
 ['9']
 ['0']
 ['4']
 ['6']
 ['4']
 ['4']
 ['1']
 ['4']
 ['9']
 ['3']
 ['0']
 ['1']
 ['3']
 ['6']
 ['9']
 ['3']
 ['1']
 ['0']
 ['1']
 ['1']
 ['1']
 ['4']]
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5425 - loss: 2.0438 
[2.0613274574279785, 0.5099999904632568]


In [4]:
clf.fit(
    x_train,
    y_train,
    # Split the training data and use the last 15% as validation data.
    validation_split=0.15,
    epochs=1,
)

In [5]:
split = 50000
x_val = x_train[split:]
y_val = y_train[split:]
x_train = x_train[:split]
y_train = y_train[:split]
clf.fit(
    x_train,
    y_train,
    # Use your own validation set.
    validation_data=(x_val, y_val),
    epochs=1,
)

In [6]:
input_node = ak.ImageInput()
output_node = ak.ImageBlock(
    # Only search ResNet architectures.
    block_type="resnet",
    # Normalize the dataset.
    normalize=True,
    # Do not do data augmentation.
    augment=False,
)(input_node)
output_node = ak.ClassificationHead()(output_node)
clf = ak.AutoModel(
    inputs=input_node, outputs=output_node, overwrite=True, max_trials=1
)
clf.fit(x_train, y_train, epochs=1)

Trial 1 Complete [00h 01m 22s]
val_loss: 2.279855251312256

Best val_loss So Far: 2.279855251312256
Total elapsed time: 00h 01m 22s
4/4 ━━━━━━━━━━━━━━━━━━━━ 66s 2s/step - accuracy: 0.1030 - loss: 4.0479


In [7]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Reshape the images to have the channel dimension.
x_train = x_train.reshape(x_train.shape + (1,))
x_test = x_test.reshape(x_test.shape + (1,))

# One-hot encode the labels.
eye = np.eye(10)
y_train = eye[y_train]
y_test = eye[y_test]

print(x_train.shape)  # (60000, 28, 28, 1)
print(y_train.shape)  # (60000, 10)
print(y_train[:3])
# array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

(60000, 28, 28, 1)
(60000, 10)
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [8]:
train_set = tf.data.Dataset.from_tensor_slices(((x_train,), (y_train,)))
test_set = tf.data.Dataset.from_tensor_slices(((x_test,), (y_test,)))

clf = ak.ImageClassifier(overwrite=True, max_trials=1)
# Feed the tensorflow Dataset to the classifier.
clf.fit(train_set, epochs=1)
# Predict with the best model.
predicted_y = clf.predict(test_set)
# Evaluate the best model with testing data.
print(clf.evaluate(test_set))

Trial 1 Complete [00h 02m 32s]
val_loss: 0.06184139847755432

Best val_loss So Far: 0.06184139847755432
Total elapsed time: 00h 02m 32s
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 160s 84ms/step - accuracy: 0.9068 - loss: 0.3032
313/313 ━━━━━━━━━━━━━━━━━━━━ 7s 21ms/step
313/313 ━━━━━━━━━━━━━━━━━━━━ 8s 25ms/step
313/313 ━━━━━━━━━━━━━━━━━━━━ 8s 24ms/step - accuracy: 0.9787 - loss: 0.0699
[0.057932525873184204, 0.982200026512146]
